### ISSUE TITLE
How to present and dismiss a tooltip on demand

### ISSUE THREAD

**Issue by chenium** [quassum/SwiftUI-Tooltip#20]
**Is your feature request related to a problem? Please describe.**
Is there a recommended procedure to accomplish the ability present and dismiss tooltips on demand? I've noticed several forks of this library that attempt to add this into the tooltip api and was wondering if there was a different recommendation from the authors.

**Describe the solution you'd like**
An api that allows us to quickly present and dismiss the tooltip. 

**Describe alternatives you've considered**
I was able to achieve this functionality by having two versions of the same view with a control statement. One with a tooltip attached and one without.

```
if showTip {
    Text("Target View")
      .tooltip {
           Text("Just the tip")
      }
} else {
    Text("Target View")
}
```

**Comment by bring-shrubbery** [comment]
Good question, there's not, but it's definitely needed, so I'll add it and close this issue when it's done ;)
